# Generated by Django 3.2.3 on 2022-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
