# Generated by Django 3.2.3 on 2022-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1950),
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
